### ISSUE TITLE
self.tif does not exist. Should it be self._tif?

### ISSUE THREAD

**Issue by gggmmm** [square/pylink#114]
Hello,

https://github.com/square/pylink/blob/a2d9fbd3add62ffd06ba737c5ea82b8491fdc425/pylink/jlink.py#L243
https://github.com/square/pylink/blob/a2d9fbd3add62ffd06ba737c5ea82b8491fdc425/pylink/jlink.py#L1065

In those two occurrences, should it be self._tif instead of self.tif?

Regards

**Comment by hkpeprah** [comment]
`tif` is a property on the instance that returns the value of `self._tif` (https://github.com/square/pylink/blob/a2d9fbd3add62ffd06ba737c5ea82b8491fdc425/pylink/jlink.py#L1674); public (`tif`) vs. private (`_tif`). Could use either.
