### ISSUE TITLE
Can this work with the open source libjaylink library?

### ISSUE THREAD

**Issue by peterpolidoro** [square/pylink#133]
Can this work with an open source library, such as libjaylink, or is this only intended to be a wrapper around the proprietary Segger SDK?

https://gitlab.zapb.de/libjaylink/libjaylink

**Comment by hkpeprah** [comment]
Hello, sorry for the late response here. Unfortunately, I don't think so, as it has it's own separate API. One could create a Python package based off of that one though.

**Comment by peterpolidoro** [comment]
Thanks!
