### ISSUE TITLE
Select SWD as target interface

### ISSUE THREAD

**Issue by ikerperezdelpalomar** [square/pylink#145]
Hi,

I am trying to connect to my board using SWD as the target interface, when using JLink this would meant executing something like:
> JLinkExe -device CHIP_NAME-if swd

Reading the docs, I can tell that `connect()` allows to specify the chip name and the target interface speed however I can't find the way to connect to the chip using SWD, is this option not supported? It seems like pylink will connect by default using Jtag, is there a way to select SWD?

I noticed that there is support to read and write from swd, but from what I understand it seems like it's meant to read and write bits not to connect to the target,

**Comment by hkpeprah** [comment]
You want to use [`set_tif`](https://pylink.readthedocs.io/en/latest/pylink.html#pylink.jlink.JLink.set_tif) (set target interface); interfaces are defined in this enum: https://pylink.readthedocs.io/en/latest/pylink.bindings.html#pylink.enums.JLinkInterfaces

**Comment by ikerperezdelpalomar** [comment]
Thank you!
