### ISSUE TITLE
Programming without erasing chip

### ISSUE THREAD

**Issue by denravonska** [square/pylink#154]
We have a system where the bootloader and some additional data need to be retained on the flash while the application can be erased. Using chip erase will nuke all of it.

I've been digging through the SDK documentation and it looks like it's possible to do using Begin- and EndDownload. It would be something like this:

```Python
data = open(path, mode="rb").read()
self._dll.JLINKARM_BeginDownload(0)
self._dll.JLINKARM_WriteMem(addr, len(data), data)
self._dll.JLINKARM.EndDownload()
```

I could give this a shot, but how would you like it implemented? Integrated into the current flash operations (`flash` and `flash_file`) or as a new function? I don't think it's possible to get a progress bar in that case, so a new function might be in order.

**Comment by hkpeprah** [comment]
I think modifying `flash()` would be the best option, and could be a major change (bump of the major version).

**Comment by denravonska** [comment]
After doing some tests it seems that progress does actually work with `WriteMem`. 

```
b'Erase' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0%  
b'Erase' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0%  
b'Compare' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 
b'Compare' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 
b'Erase' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 
b'Program' |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 
```
