### ISSUE TITLE
Specify JLinkScript file

### ISSUE THREAD

**Issue by gw826943555** [square/pylink#188]
Hi, 

I am now trying to connect a dual-core cortex-r5. We use `-JLinkScriptFile` command to specify the JLinkScript file and connect the core I'd like to connect. 
`JLink.exe -JLinkScriptFile xxx_path\R5_ConnectCore0.JLinkScript`
`JLink.exe -JLinkScriptFile xxx_path\R5_ConnectCore1.JLinkScript`
It works fine. 

My question is whether pylink support this feature.

Thanks!

**Comment by hkpeprah** [comment]
PyLink does not support the scripts. The scripts are essentially commands / function calls. You will need to translate your scripts into the appropriate function calls.

**Comment by gtowers-dukosi** [comment]
@hkpeprah -JLinkScriptFile does **not** specify a sequence of command function calls. You're getting confused with the -CommanderScript option.

JLinkScriptFile is a C-like syntax that allows you to customise internal actions, most notably what happens on a device reset to allow for hardware-specific requirements that cannot be easily dealt with through the standard J-Link API.
See https://wiki.segger.com/J-Link_script_files for more details.

I agree that supporting JLinkScriptFiles would be a really useful feature add for the module, as their lack limits what can be done with the module.

**Comment by gtowers-dukosi** [comment]
The DLL is normally somewhere in _"C:\Program Files (x86)\"_, which on most machines needs admin privileges for an application to write to, so that's probably not going to work - but I like your thinking. Thanks for reading up, I'd missed that section on the page - very interesting to know that it's parsed by the .dll rather than the .exe. That suggests there must be another way to somehow specify a custom filepath directly to the DLL.

**Comment by hkpeprah** [comment]
By default, we copy the library file to a separate temporary folder (unless you specify otherwise). So we should be able to write the `Default` script into that folder, and delete it when we clean-up the temporary library file as well.

**Comment by gtowers-dukosi** [comment]
Sounds like it might just work then! I think it would meet my requirements in any case.
Thanks again

**Comment by gtowers-dukosi** [comment]
I found a better solution! This does exactly what I need:
`jlink.exec_command("scriptfile = C:\\path\\to\\myJlinkScript.JLinkScript")`

Technically no pylink upfates even needed for pylink, but since it's not at all obvious I think a pylink wrapper function for that command would be a nice feature.

**Comment by hkpeprah** [comment]
Nice! That is much simpler. If you want to submit a patch for the new function, I can accept it. Something like `set_script()`?

**Comment by hkpeprah** [comment]
This is now available via `set_script_file()` in `v1.3.0` thanks to @gtowers-dukosi!
