### ISSUE TITLE
Downloading Firmware image to Cortex Fails

### ISSUE THREAD

**Issue by engrnader** [square/pylink#195]
Hi,
When downloading `.bin` or `.axf` using `jlink.flash_file(firmware_image, 0x0)` fails to download to DUT's memory. I'm using this correctly? 
Alternatively, when using `jlink commander` provided by SEGGER and use the following command,
```
loadbin <firmware_path.bin> 0X0
```
works perfectly. 

Can someone assist me with this?

**Comment by hkpeprah** [comment]
Can you paste your code, and logs? Verbose logging can be enabled by doing the following:
```
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by engrnader** [comment]
This issue has been resolved.
