### ISSUE TITLE
Do I need to use jlink.connect before doing jlink.rtt_start?

### ISSUE THREAD

**Issue by ephraim271** [square/pylink#198]
Checking if I can start rtt without doing a jlink.connect()?

rtt_start() says only "open required", not "connect required". 
But without doing a jlink.connect(), rtt_get_status() is always returns zero. 

Usecase : I want to keep sending data on rtt without considering if target is powered on or not.

**Comment by hkpeprah** [comment]
To use RTT, the debugger needs to be able to read from target memory on the device. If the device is not powered, then you would not be able to read from its memory. I think you would have to figure an out-of-band way of knowing whether your target is powered or not if you want to use RTT without attempting a connection if it's possible that your target is not powered.

**Comment by ephraim271** [comment]
Thank you for the quick response! 
So I'll go with a hacky solution.. I put `open/connect/rtt_start` into a while loop till I get a positive rtt_get_status() when target gets turned on :)
