### ISSUE TITLE
Cannot connect to J-Link when multiple jlinks are active

### ISSUE THREAD

**Issue by ephraim271** [square/pylink#203]
I've 2 jlinks connected to 2 mcus, with ozone. 
I want to use pylink to send data via rtt. 
When there are 2 jlinks, jlink.open(serial_num) for one of the jlink doesn't seem to work. 
`An error occurred: Cannot connect to jlink`

**Comment by hkpeprah** [comment]
Do you have sample code?

**Comment by ephraim271** [comment]
Hi - I'm not able to reproduce this for now, so closing this.
