### ISSUE TITLE
Dual-Bank devices cannot be programmed, e.g. STM32G473VE

### ISSUE THREAD

**Issue by 1614508410** [square/pylink#205]
![image](https://github.com/user-attachments/assets/5794ca3b-9246-494a-a68e-b058360eb237)
Programming error occured.

**Comment by hkpeprah** [comment]
Can you provide logs from your attempt?
```
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by 1614508410** [comment]
Sorry, I just saw that ,I replaced the latest dynamic link library, and this problem has been solved.
