### ISSUE TITLE
Disable popups

### ISSUE THREAD

**Issue by johncharlie** [square/pylink#41]
When using an STM32 board as a JLink device, every day a popup appears so you cannot execute scripts in an automated manner, because you need to close the window. Is it possible to disable all the popups?

**Comment by hkpeprah** [comment]
After you create the instance, you can can call `.disable_dialog_boxes()`.  This has the effect of disabling the boxes that pop-up for FW update, and switches it to batch mode so that you don't get prompted.
```
jlk = pylink.JLink()
jlk.disable_dialog_boxes()
<rest of stuff>
```

**Comment by johncharlie** [comment]
Thanks, will test and update the issue if it works for all popups.

**Comment by johncharlie** [comment]
It does not work with this popup:

![image](https://user-images.githubusercontent.com/4211039/45236597-e36f4880-b2a1-11e8-9fd8-67f0da3c2c75.png)

**Comment by hkpeprah** [comment]
Hm.  That seems to not be dismissible (only some are).  Given the box that says "Do not show this message again for today" and the terms of use, I don't think it's intended for batch mode.

**Comment by sstallion** [comment]
It might be worth opening a support ticket with SEGGER to see if there is
another method you can use to silence those popups - that's awfully
frustrating.

**Comment by johncharlie** [comment]
Will do. Thanks.

**Comment by johncharlie** [comment]
After talking with SEGGER support, only way to suppress this popup is by using a JLink device and connecting it to the STLink board. The popup cannot be disabled since this support (converting STLink device as JLink device) is only for evaluation purposes. Thanks, I will close the issue.

**Comment by sstallion** [comment]
Thanks Juan, I'm sorry there isn't something more we can do.
