### ISSUE TITLE
how to get RTT buffer size?

### ISSUE THREAD

**Issue by tianxiaoMCU** [square/pylink#48]
The J-Link RTT Viewer can get channel description include buffer size,like below
![channel info](https://user-images.githubusercontent.com/40310665/51648833-2023ae00-1fbd-11e9-9e87-684dd9115d16.png)
Is there a API to do this? I try rtt_control,but failed.

**Comment by hkpeprah** [comment]
Doesn't seem like we expose this yet.  `rtt_control` is the method to use, I believe.

**Comment by sstallion** [comment]
It might be worth scoping this out and creating a ticket.

**Comment by tarakanov** [comment]
+1 for this feature. I use RTT for debugging and cannot send strings more than 14 characters long (for 16 bytes down buffer)

**Comment by hkpeprah** [comment]
Should be available now in [v0.6.0](https://github.com/square/pylink/releases/tag/0.6.0).
