### ISSUE TITLE
provide a way to read/write system control coprocessor CP15

### ISSUE THREAD

**Issue by Sauci** [square/pylink#61]
According to [this](http://webcache.googleusercontent.com/search?q=cache:http://read.pudn.com/downloads214/sourcecode/embed/1007183/jlink/jlinkarm.h__.htm) link, the DLL seems to provide some functions to access the **CP15**:
- ```JLINKARM_CP15_IsPresent```
- ```JLINKARM_CP15_ReadEx```
- ```JLINKARM_CP15_ReadReg```
- ```JLINKARM_CP15_WriteEx```
- ```JLINKARM_CP15_WriteReg```

However, I can't find any of those functions in the project.

I tried to call the ```long __declspec(dllimport) JLINKARM_CP15_IsPresent()``` (signature available in previously mentioned link):

```python
@connection_required
def cp15_present(self):
    """Returns whether target has CP15 co-processor.

    Returns:
        ``True`` if the target has CP15 co-processor, otherwise ``False``.
    """
    result = False
    if self._dll.JLINKARM_CP15_IsPresent() != 0:
        result = True
    return result
```

and it doesn't crash.

I would be happy to implement this functionality, but the content of the header file in the link does not provide enough documentation to do it.

**Comment by hkpeprah** [comment]
Currently we do not have bandwidth to address this feature, but if you're interested in working on it, I'll gladly merge the feature.  You'll have to purchase the SDK for the manufacturer for documentation.
