### ISSUE TITLE
Detect connected debugger

### ISSUE THREAD

**Issue by Viatorus** [square/pylink#92]
Is it possible to get a list of all connected debuggers so one could select one of those instead of providing a serial number?

**Comment by hkpeprah** [comment]
Yup.  You can do so using the [`connected_emulators()`](https://pylink.readthedocs.io/en/latest/pylink.bindings.html#pylink.structs.JLinkConnectInfo) method, which returns a list of connection information devices, see the [docs here](https://pylink.readthedocs.io/en/latest/pylink.html#pylink.jlink.JLink.connected_emulators).  You can then use the returned list to figure out the serial number of IP address to pass to your call to `open()`.

**Comment by Viatorus** [comment]
Great, thank you! I was confused by the name emulator.
